services:
  wg-easy:
    container_name: wg-easy
    restart: always
    environment:
      - WG_HOST=
      # https://github.com/wg-easy/wg-easy/blob/master/How_to_generate_an_bcrypt_hash.md
      - PASSWORD_HASH=
      - PORT=51821
      - WG_PORT=123
    volumes:
      - ./config/wg-easy:/etc/wireguard
    ports:
      - 123:123/udp
      - 51821:51821/tcp
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv4.ip_forward=1
    image: ghcr.io/wg-easy/wg-easy
